create table users(
                      id         integer generated by default as identity,
                      login         varchar(30),
                      password           varchar(255),
                      primary key (id));
insert into users(login, password)
values ('admin','$2a$10$expPYNAwuWOQ8VUkeOj2jOAxcZ6w6piGOONSaRFgq2jLTWM4Kz6i6'),
       ('user','$2a$10$BJoR88hexuk790LLD18Ni.jf9fytcFBCpCs9pWuLADvXYJ4ISUXKi');

create table accounts(
                         id INTEGER generated by default as identity,
                         number          varchar(20),
                         amount float,
                         user_id integer,
                         foreign key (user_id) references users(id),
                         primary key (id));
insert into accounts(number, amount, user_id)
values (582263,5000,2);

create table clients(
                        id integer generated by default as identity,
                        name    varchar(30),
                        surname    varchar(30),
                        user_id integer,
                        foreign key (user_id) references users(id),
                        primary key (id));
insert into clients(name, surname, user_id)
values ('Иван','Мельников',2);

create table roles(
                      id integer generated by default as identity,
                      role    varchar(30),
                      primary key (id));
insert into roles(role)
values ('role_Admin'),
       ('role_User');

create table roles_users(
                            user_id    integer,
                            role_id    integer,
                            foreign key (user_id) references users(id),
                            foreign key (role_id) references roles(id));


