create table accounts(
                         id INTEGER generated by default as identity,
                         number          varchar(20),
                         amount float,
                         primary key (id));

create table clients(
                        id integer generated by default as identity,
                        name    varchar(30),
                        surname    varchar(30),
                        account_id integer,
                        foreign key (account_id) references accounts(id),
                        primary key (id));

create table users(
                      id         integer generated by default as identity,
                      login         varchar(30),
                      password           varchar(255),
                      client_id        integer,
                      foreign key (client_id) references clients(id),
                      primary key (id));

create table roles(
                      id integer generated by default as identity,
                      role    varchar(30),
                      primary key (id));
insert into roles(role)
values ('role_Admin'),
       ('role_User');

create table roles_users(
                            user_id    integer,
                            role_id    integer,
                            foreign key (user_id) references users(id),
                            foreign key (role_id) references roles(id));


